### ISSUE TITLE
Memory leak in createFromOnnxValue

### ISSUE THREAD

**Issue by DrDub** [ankane/onnxruntime-php#2]
Hi,

I'm using onnxruntime-php in [textualization/php-semantic-search](https://github.com/Textualization/php-semantic-search). When indexing thousands of documents the memory consumption balloons up several gigs.

Looking at your code, there is this comment in `SessionInference run()`

```php
        // output values released in create_from_onnx_value
```

However, the memory release code in `SessionInference createFromOnnxValue()` seems to be missing.

If that's a known bug, we can look into fixing it or waiting for a fix. Otherwise we'll look into something else as the reason behind the memory usage.

Thanks for making onnxruntime-php available!

**Comment by ankane** [comment]
Hi @DrDub, thanks for reporting! Fixed in the commit above. Can you try running the latest version from GitHub to confirm?

Edit: [Diff without whitespace changes](https://github.com/ankane/onnxruntime-php/commit/a1883d3ae5c5b73d36745f27e71ed5dd8f9c8513?w=1)

**Comment by DrDub** [comment]
Lovely! Let me try it and I'll report back.

**Comment by DrDub** [comment]
Fix confirmed. It went down from 22G over 20h exectution to 1G stable all throughout. Thanks so much for the fix!

**Comment by ankane** [comment]
Great, thanks for checking. Just pushed a new release (0.1.7).
